# -*- coding: utf-8 -*-
"""Gooden.Craig-PythonCode-ITT103-F2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QM97yr9dpE8JEdlkz0iaV9YAB0XcXiV
"""

"""
Author: Craig Gooden
Date Created: 2023-12-09
Course: ITT103 Programming Techniques
Purpose: This program handles seat reservations for first-class, business-class, and economy-class bus travel for UCC Signature Express Limited
"""

# Here we Define the Bus Classes
class Bus:
    def __init__(self, capacity, bus_class):
        self.capacity = capacity
        self.bus_class = bus_class
        self.remaining_seats = capacity

# Initialize bus objects for each class
first_class_bus = Bus(27, "First-Class")
business_class_bus = Bus(38, "Business-Class")
economy_class_bus = Bus(56, "Economy-Class")


def reserve_seat(bus, passenger_name):
    # Check if seats are available in the chosen bus class
    if bus.remaining_seats > 0:
        # Assign seat and update remaining seats
        bus.remaining_seats -= 1
        print(f"Seat successfully reserved for {passenger_name} in {bus.bus_class} bus.")
    else:
        print(f"Sorry, {bus.bus_class} bus is full.")


def main():
    # This is the Welcome message
    print("Welcome to UCC Signature Express Limited Bus Reservation System!")

    # The User will be choose their travel class
    travel_class = input("Please select your travel class (First, Business, Economy): ")

    # Let's Validate the user input
    if travel_class.lower() not in ["first", "business", "economy"]:
        print("Invalid travel class entered. Please try again.")
        return

    #   passenger name is entered here
    passenger_name = input("Enter your name: ")

    # Choose the appropriate bus option based on travel class
    if travel_class.lower() == "first":
        reserve_seat(first_class_bus, passenger_name)
    elif travel_class.lower() == "business":
        reserve_seat(business_class_bus, passenger_name)
    else:
        reserve_seat(economy_class_bus, passenger_name)


if __name__ == "__main__":
    main()